services:
  backend:
    build: ./backend
    container_name: pims_backend
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pims_db:5432/pims_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:15-alpine
    container_name: pims_db
    restart: always
    environment:
      - POSTGRES_DB=pims_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: pims_frontend
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - web

networks:
  web:
    external: true
